
server:
  port: 8080

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [uuid=%X{correlationId}] %logger{36} : %msg%n"
  level:
    com.core.cashin: DEBUG

spring:
  # 1. Datasource Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/payments?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  # 2. Redis Configuration
  data:
    redis:
      url: ${REDIS_URL:redis://localhost:6379}

  # 3. JPA/Hibernate Configuration
  jpa:
    show-sql: true # Log SQL statements
    hibernate:
      ddl-auto: none # Options: none, update, create, create-drop, validate
    properties:
      hibernate:
        # Specifies the MySQL Dialect for Hibernate
        dialect: org.hibernate.dialect.MySQLDialect

oauth:
  state:
    ttl-minutes: 10

mercadopago:
  client-id: ${MERCADOPAGO_CLIENT_ID:3792571553313307}
  client-secret: ${MERCADOPAGO_CLIENT_SECRET:qF9NtkZYeOD8Rvy0wutPZY8pQWN9JvQE}
  redirect-uri: ${MERCADOPAGO_REDIRECT_URI:https://unculturable-tyree-nonveritably.ngrok-free.dev/api/v1/oauth/callback}
  api-url: ${MERCADOPAGO_API_URL:https://api.mercadopago.com}

jobs:
  created-to-cancelled:
    cron: "0 0 */8 * * *"
  pending-to-cancel:
    cron: "0 0/10 0 */3 * *"
    zone: America/Mexico_City
  refresh-token-oauth:
    cron: "0 0 0 * * *"
    zone: America/Mexico_City

resilience4j:
  circuitbreaker:
    instances:
      mercadoPagoCB:
        # TIPO DE VENTANA
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 20              # Mira las últimas 20 peticiones
        # CUÁNDO EMPEZAR A EVALUAR
        minimumNumberOfCalls: 10           # No decide nada hasta tener al menos 10 llamadas
        # UMBRALES DE FALLO (ERROR EXPLICITO)
        failureRateThreshold: 50           # Si 5 de esas 10 fallan (50%), abre el circuito
        # UMBRALES DE LENTITUD (LATENCIA) - ¡MUY IMPORTANTE!
        slowCallDurationThreshold: 3s      # Si tarda más de 3s, se considera "lenta"
        slowCallRateThreshold: 50          # Si el 50% de las llamadas son lentas, abre el circuito
        # RECUPERACIÓN
        waitDurationInOpenState: 30s       # Si se abre, espera 30s antes de intentar de nuevo
        permittedNumberOfCallsInHalfOpenState: 5 # Deja pasar 5 llamadas de prueba tras la espera
        automaticTransitionFromOpenToHalfOpenEnabled: true
        recordExceptions:
          - com.mercadopago.exceptions.MPException
          - java.util.concurrent.TimeoutException
          - java.io.IOException
          - com.core.cashin.commons.exception.InternalServerException
        ignoreExceptions:
          - com.core.cashin.commons.exception.BadRequestException

      mercadoPagoCheckoutApiCB:
        # TIPO DE VENTANA
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 20              # Mira las últimas 20 peticiones
        # CUÁNDO EMPEZAR A EVALUAR
        minimumNumberOfCalls: 10           # No decide nada hasta tener al menos 10 llamadas
        # UMBRALES DE FALLO (ERROR EXPLICITO)
        failureRateThreshold: 50           # Si 5 de esas 10 fallan (50%), abre el circuito
        # UMBRALES DE LENTITUD (LATENCIA)
        slowCallDurationThreshold: 3s      # Si tarda más de 3s, se considera "lenta"
        slowCallRateThreshold: 50          # Si el 50% de las llamadas son lentas, abre el circuito
        # RECUPERACIÓN
        waitDurationInOpenState: 30s       # Si se abre, espera 30s antes de intentar de nuevo
        permittedNumberOfCallsInHalfOpenState: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        recordExceptions:
          - feign.FeignException.InternalServerError
          - feign.FeignException.ServiceUnavailable
          - feign.FeignException.GatewayTimeout
          - java.util.concurrent.TimeoutException
          - java.io.IOException
          - com.core.cashin.commons.exception.InternalServerException
        ignoreExceptions:
          - com.core.cashin.commons.exception.BadRequestException
          - com.core.cashin.commons.exception.NotFoundException